### PR TITLE
Fix FireMonkey compatibility

### LINKED ISSUE #251: Additional stats don't load on own profile in Firefox, most of the time
Previously mentioned in #49 and supposedly fixed in #93 but most of the time it doesn't work for me on Firefox, with the userscript installed with Greasemonkey. (and if installed with FireMonkey, the feature doesn't work on _any_ profiles)

Seems to look a little different from #49's description; instead of loading forever on the "More Stats" section it just says nothing where the stats ordinarily would be:
image
"Genre & Tags" does load forever, though:
image

And of course, another difference from #49 is that it sometimes works? When I first installed Greasemonkey to see if it would work, it loaded fine, and then didn't work at all for subsequent attempts, except for one time I alt-tabbed into it (don't remember if I refreshed too?) and it worked when I clicked on the sections again.

For the second working attempt, I remember seeing `Multiple copies of the script running? Shutting down this instance` in the console. Not sure if it's related or if it's just because I had multiple AniList tabs open, or because I have multiple userscript managers installed (with the userscript disabled in FireMonkey while testing with Greasemonkey), or something else.

Persistent storage does seem to be enabled:
image
and if I look at the storage section of devtools, there is Automail related stuff in session storage, local storage and Indexed DB, so I'm pretty sure that's working fine.

Console output:
image
The last two lines seem to be directly related to the issue, with the supposedly problematic code (with line numbers added and indents removed for readability) being:
```js
21506	if(entry.isCustomList){
21507		entry.listLocations = [mediaList.name] // Error on this line
21508	}
21509	else{
21510		entry.listLocations = [] // Error on this line
21511	}
````

### PR DESCRIPTION
**Pull request by kazzarin**
Fixes #251
- used [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) to resolve Xray error
  - a shallow clone like ```const entry = {..._entry}``` didn't work because it would still error on the `entry.media` object
  - todo: look for a polyfill since it's a newer feature
- no longer depend on cache.js in stats module (mostly)
  - apiv2 can handle caching lists in a similar way
  - (this didn't have any effect on the main issue, though i changed it to rule it out anyways)
- fixed another GM xhr check for mal recs
  - removed the xhr backup as that will fail anyways because of cors
  - (might look into using jikan for this instead)

### CODE REVIEW

**Comment by hohMiyazawa** [comment]
Newer features should not be used naked. Wrap it in a ``if(window.structuredClone)``, and fall back to the old code when it fails.

Alternatively, we don't need a more advanced polyfill than ``function(item){return item}`` for now.

File: src/modules/addMALscore.js [hunk 1]
```diff
@@ -114,20 +114,14 @@ async function addMALscore(type,id){
 					adder()
 				}
 			}
-			if(window.GM_xmlhttpRequest){
+			if(GM_xmlhttpRequest){
```
Comment (hohMiyazawa) [inline src/modules/addMALscore.js:117]: This doesn't work. Throws an error if no such thing is defined.

File: src/modules/addMALscore.js [hunk 2]
```diff
@@ -114,20 +114,14 @@ async function addMALscore(type,id){
...
 					url: "https://myanimelist.net/" + type + "/" + data.data.Media.idMal + "/placeholder/userrecs",
 					onload: function(response){handler(response)}
 				})
 			}
-			else{
-				let oReq = new XMLHttpRequest();
-				oReq.addEventListener("load",function(){handler(this)});
-				oReq.open("GET","https://myanimelist.net/" + type + "/" + data.data.Media.idMal + "/placeholder/userrecs");
-				oReq.send()
-			}
```
Comment (hohMiyazawa) [inline src/modules/addMALscore.js:130]: This still works AFAIK in some browsers.

File: src/modules/addMoreStats.js [hunk 3]
```diff
@@ -1767,10 +1767,17 @@ function addMoreStats(){
 	}//end boneless check
 			return
 		};
-		if(user === whoAmI && reliablePersistentStorage){
-			cache.getList("ANIME",function(data){
-				personalStatsCallback(data)
-			})
+		if(user === whoAmI){
```
Comment (hohMiyazawa) [inline src/modules/addMoreStats.js:1770]: Does APIv2 have its own equivalent of ``reliablePersistentStorage``?

File: src/modules/addMALscore.js (hunk 1 above)
Comment (kazzarin) [reply src/modules/addMALscore.js]: oops, fixed it

File: src/modules/addMALscore.js (hunk 2 above)
Comment (kazzarin) [reply src/modules/addMALscore.js:130]: Huh, I didn't know that

Comment (kazzarin) [reply src/modules/addMALscore.js]: added it back, though it wasn't working for me when forcing xhr in FF or Edge

File: src/modules/addMoreStats.js (hunk 3 above)
Comment (kazzarin) [reply src/modules/addMoreStats.js:1770]: well it also uses localforage for cache which falls back to localStorage automatically if IndexedDb/persistent storage is unavailable

**Comment by kazzarin** [comment]
put the check on structuredClone. the polyfills available weren't that simple so it probably isn't worth it for this single use case
